apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-xzjv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-brpj-tenant/rhtap-demo-app/hacbs-test-project-xzjv@sha256:5056411aafe4a6304f3634d37b9790be3dc22c34e201adc313451129a95163cb
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
